
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Adnan
 */
public class studentDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    Connection con = null;

    public studentDetails() {
        initComponents();

        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");

        Date date = new Date();

        jLabel7.setText(dFormat.format(date));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ID.png"))); // NOI18N
        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 80));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 220, 30));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/User.png"))); // NOI18N
        jLabel5.setText("UserName");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/quit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 90, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/exitIcon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 80, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/loginIcon.png"))); // NOI18N
        jButton3.setText("Sign In ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 140, 70));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 220, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/searchIcon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 120, 70));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 120, 20));

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Password.png"))); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/student.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 70));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel6.setText(" Date : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 90, 40));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setText("STUDENT INFO ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/studenBG.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 520));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 220, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new index().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);

        int a = JOptionPane.showConfirmDialog(jf, "Confirm Exit?", "Select", JOptionPane.YES_NO_OPTION);

        if (a == 0) {
            System.exit(0);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String IDSTUDENT = jTextField1.getText();
        String USERNAMESTUDENT = jTextField2.getText();
        String passWord = jPasswordField1.getText();
        String marks = "0";
        int row = -1;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/STUDENT", "STUDENT", "STUDENT");

            if (IDSTUDENT.equals("") || USERNAMESTUDENT.equals("") || passWord.equals("") || marks.equals("")) {
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "One or more fields are Empty", "Error", JOptionPane.INFORMATION_MESSAGE);

            } else if (checkDuplicateID(IDSTUDENT)) {
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "This ID already exists!", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String sql = "INSERT INTO STUDENT (IDSTUDENT,NAMESTUDENT, PASSWORD , MARKS ) VALUES (?,?,?,?)";

                PreparedStatement ps = con.prepareCall(sql);
                ps.setString(1, IDSTUDENT);
                ps.setString(2, USERNAMESTUDENT);
                ps.setString(3, passWord);
                ps.setString(4, marks);

                row = ps.executeUpdate();
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                //JOptionPane.showMessageDialog(jf, "Data insertion Successful" + row, "info", JOptionPane.INFORMATION_MESSAGE);

                setVisible(false);
                new instructionStudent(IDSTUDENT).setVisible(true);
            }

        } catch (Exception ex) {
            Logger.getLogger(addNewQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String IDSTUDENT = jTextField1.getText();
        String USERNAMESTUDENT = jTextField2.getText();
        String passWord = jPasswordField1.getText();
        String marks = "0";

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/STUDENT", "STUDENT", "STUDENT");

            if (IDSTUDENT.equals("") || USERNAMESTUDENT.equals("") || passWord.equals("") || marks.equals("")) {
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "One or more fields are Empty", "Error", JOptionPane.INFORMATION_MESSAGE);

            } else if (checkDuplicateID(IDSTUDENT)) {
                String sql = "SELECT * FROM STUDENT WHERE IDSTUDENT = ?"; // SELECT * FROM ADNAN WHERE ID='" + id + "'" ; 
                ResultSet rs = null;

                PreparedStatement predata;

                predata = con.prepareStatement(sql);

                predata.setString(1, IDSTUDENT);

                rs = predata.executeQuery();

                if (rs.next()) {
                    String StudentName = (rs.getString(2));
                    String StudentMark = (rs.getString(4));
                    String STUDENTpassWord = (rs.getString(3));

                    if (!STUDENTpassWord.equals(passWord)) {
                        JFrame jf = new JFrame();
                        jf.setAlwaysOnTop(true);

                        JOptionPane.showMessageDialog(jf, "Wrong Password");
                    }
                    else {
                        new searchResultStudent(IDSTUDENT, StudentName, StudentMark).setVisible(true);
                        this.setVisible(false);
                    }
                    

                } else {
                    JFrame jf = new JFrame();
                    jf.setAlwaysOnTop(true);

                    JOptionPane.showMessageDialog(jf, "Requested ID does Not Exists!");
                }

            } else {
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "Give Exam First", "Error", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(studentDetails.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean checkDuplicateID(String username) {
        PreparedStatement st;

        ResultSet rs;
        boolean usernameexist = false;
        String query = "SELECT * FROM STUDENT WHERE IDSTUDENT=?";
        try {

            st = con.prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            if (rs.next()) {
                usernameexist = true;

            }
        } catch (SQLException ex) {
            // Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return usernameexist;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
